# services to handle doctrine extensions
services:
    # KernelRequest listener
    extension.listener:
        class: App\CoreBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
            # loggable hooks user username if one is in security context
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    # Doctrine Extension listeners to handle behaviors
#    gedmo.listener.tree:
#        class: GedmoTreeTreeListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]

#    gedmo.listener.translatable:
#        class: GedmoTranslatableTranslatableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]
#            - [ setDefaultLocale, [ %locale% ] ]
#            - [ setTranslationFallback, [ false ] ]

#    gedmo.listener.timestampable:
#        class: GedmoTimestampableTimestampableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]

#    gedmo.listener.sluggable:
#        class: GedmoSluggableSluggableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]

#    gedmo.listener.sortable:
#        class: GedmoSortableSortableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]

#    gedmo.listener.loggable:
#        class: GedmoLoggableLoggableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]