security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                remember_me:            true
                provider:               fos_userbundle
                success_handler:        authentication_handler
                failure_handler:        authentication_handler
                check_path:             security_check
                login_path:             security_login
                csrf_provider:          form.csrf_provider
                default_target_path:    homepage
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inside/, role: ROLE_ADMIN }
        - { path: ^/category, role: ROLE_ADMIN }